EM.Web/Models/ErrorViewModel.cs
namespace EM.Web.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

EM.Web/Controllers/AlunoController.cs
using EM.Domain.Models;
using EM.Domain.Utilitary;
using EM.Repository.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace EM.Web.Controllers;

public class AlunoController : Controller
{
    readonly private AlunoRepository _alunoRepository;

    public AlunoController(AlunoRepository alunoRepository)
    {
        _alunoRepository = alunoRepository;
    }

    public async Task<IActionResult> Index(string searchString, string searchType)
    {
        IEnumerable<Aluno> alunos = new List<Aluno>();

        if (!string.IsNullOrEmpty(searchString))
        {
            if (searchType == "id")
            {
                try
                {
                    if (int.TryParse(searchString, out int id))
                    {
                        var alunoPesquisado = await _alunoRepository.GetByMatricula(id);
                        if (alunoPesquisado is not null)
                        {
                            ((List<Aluno>)alunos).Add(alunoPesquisado);
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    alunos = await _alunoRepository.GetAllAsync();
                }
            }
            else if (searchType == "nome")
            {
                alunos = await _alunoRepository.GetByContendoNoNome(searchString);
            }
            else
            {
                Console.WriteLine("Método de pesquisa inválido");
            }
        }
        else
        {
            alunos = await _alunoRepository.GetAllAsync();
        }

        var alunoViewModel = new AlunoViewModel
        {
            Alunos = alunos!.ToList(),
            SearchString = searchString,
            SearchType = searchType,
        };

        return View(alunoViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Cadastrar(Aluno aluno)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _alunoRepository.AddAsync(aluno);
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        return View("Editar", aluno);

    }

    public async Task<IActionResult> Editar(int? id)
    {
        if(id == null)
        {
            return View("Editar");
        }
        else
        {
            var aluno = await _alunoRepository.GetByMatricula((int)id);
            if(aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }
    }


    [HttpPost]
    public async Task<IActionResult> Editar(int id, Aluno aluno)
    {
        if(id != aluno.Matricula)
        {
            return NotFound();
        }

        if(ModelState.IsValid)
        {
            try
            {
                await _alunoRepository.UpdateAsync(aluno);
            }
            catch(Exception)
            {
                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        return View(aluno);
    }

    public async Task<IActionResult> Excluir(int? id)
    {
        if(id == null)
        {
            return NotFound();
        }

        var aluno = await _alunoRepository.GetByMatricula((int)id);

        if(aluno == null)
        {
            return NotFound();
        }

        return View(aluno);
    }

    [HttpPost, ActionName("Excluir")]
    public async Task<IActionResult> ExcluirConfirmado(int id)
    {
        await _alunoRepository.RemoveAsync(new Aluno { Matricula = id });

        return RedirectToAction(nameof(Index));
    }

	//só gera
	//public async void Imprime()
	//{
	//    var listaDeAlunos = await _alunoRepository.GetAllAsync();
	//    iText.GerarRelatorioPDF(listaDeAlunos.Count(), listaDeAlunos.ToList());
	//}

	//gera e baixa
	//public async Task<IActionResult> Imprime()
	//{
	//	var listaDeAlunos = await _alunoRepository.GetAllAsync();
	//	var filePath = iText.GerarRelatorioPDF(listaDeAlunos.Count(), listaDeAlunos.ToList());

	//	// Verifica se o arquivo existe
	//	if (System.IO.File.Exists(filePath))
	//	{
	//		var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
	//		var contentType = "application/pdf";
	//		var fileDownloadName = "relatorio.pdf"; // Nome do arquivo que será baixado pelo cliente

	//		return File(fileStream, contentType, fileDownloadName);
	//	}
	//	else
	//	{
	//		// Se o arquivo não existir, retorna um erro 404
	//		return NotFound();
	//	}
	//}


	public async Task<IActionResult> Imprime()
	{
		var listaDeAlunos = await _alunoRepository.GetAllAsync();
		var filePath = iText.GerarRelatorioPDF(listaDeAlunos.Count(), listaDeAlunos.ToList());

		// Verifica se o arquivo existe
		if (System.IO.File.Exists(filePath))
		{
			var fileBytes = System.IO.File.ReadAllBytes(filePath);
			var contentType = "application/pdf";

			return File(fileBytes, contentType);
		}
		else
		{
			// Se o arquivo não existir, retorna um erro 404
			return NotFound();
		}
	}
}

EM.Web/Views/Aluno/Editar.cshtml
@model Aluno
@{
	ViewData["title"] = Model is null || Model.Matricula == 0 || Model.Matricula is null ? "Cadastrar" : "Editar" + " Aluno";
}

<h1>@(Model is null || Model.Matricula == 0 || Model.Matricula is null ? "Cadastrar" : "Editar")</h1>
<hr />

<div class="row">

	<div class="col-md-4">

		<form asp-action="@(Model is null || Model.Matricula == 0 || Model.Matricula is null ? "Cadastrar" : "Editar")" method="post">

			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			@if(Model is not null || Model?.Matricula != 0)
			{
				<input asp-for="Matricula" type="hidden"/>				
			}
			<div class="form-group">
				<label asp-for="Nome" class="control-label"></label>
				<input id="nomeInput" asp-for="Nome" class="form-control" />
				<span asp-validation-for="Nome" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CPF" class="control-label"></label>
				<input id="cpfInput" asp-for="CPF" class="form-control"/>
				<span asp-validation-for="CPF" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Nascimento" class="control-label"></label>
				<input min="1800-01-01" max="2199-12-31" asp-for="Nascimento" class="form-control"/>
				<span asp-validation-for="Nascimento" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Sexo" class="control-label"></label>
				<select asp-for="Sexo" class="form-control">
					<option value="Masculino">Masculino</option>
					<option value="Feminino">Feminino</option>
				</select>
				<span asp-validation-for="Sexo" class="text-danger"></span>
			</div>

			<br />

			<div class="form-group">
				<input type="submit" value="@(Model is null || Model.Matricula == 0 || Model.Matricula is null? "Cadastrar" : "Salvar")" class="btn btn-primary" /> | 
				<a asp-controller="Aluno" asp-action="Index">Voltar para a lista</a>
			</div>

		</form>

	</div>

</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

EM.Web/Views/Aluno/Excluir.cshtml
@model Aluno
@{
    ViewData["title"] = "Excluir Aluno";
}

<h1>Excluir</h1>
<h3>Tem certeza que deseja excluir este aluno?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>

    <form asp-action="Excluir">
        <input type="hidden" asp-for="Matricula" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para a lista</a>
    </form>
</div>

EM.Web/Views/Aluno/Index.cshtml
@model AlunoViewModel
@{
	ViewData["Title"] = "Aluno";
}

<h1>Alunos</h1>
<br />
<br />

<a class = "btn btn-success" asp-controller="Aluno" asp-action="Editar">Cadastrar Aluno</a>
<br />
<br />

<form asp-controller="Aluno" asp-action="Index" method="get">
	<p>
		<label>
			<input type="radio" asp-for="SearchType" value="id" checked/> Filtrar por ID
		</label>

		<label>
			<input type="radio" asp-for="SearchType" value="nome" /> Filtrar por nome
		</label>
	</p>
	<p>
		Filtro: <input type="text" asp-for="SearchString" />
		<input type="submit" value="Filter" />
	</p>
</form>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Alunos![0].Matricula)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Alunos![0].Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Alunos![0].CPF)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Alunos![0].Nascimento)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Alunos![0].Sexo)
			</th>
			<th></th>
		</tr>
	</thead>

	<tbody>

		@foreach(var aluno in Model.Alunos!)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => aluno.Matricula)
				</td>
				<td>
					@Html.DisplayFor(modelItem => aluno.Nome)
				</td>
				<td>
					@Html.DisplayFor(modelItem => aluno.CPF)
				</td>
				<td>
					@Html.DisplayFor(modelItem => aluno.Nascimento)
				</td>
				<td>
					@Html.DisplayFor(modelItem => aluno.Sexo)
				</td>
				<td>
					<a class="btn btn-primary" asp-controller="Aluno" asp-action="Editar" asp-route-id="@aluno.Matricula">Editar</a>
					<a class="btn btn-warning" asp-controller="Aluno" asp-action="Excluir" asp-route-id="@aluno.Matricula">Excluir</a>
				</td>
			</tr>
		}
	</tbody>
</table>



<a asp-controller="Aluno" asp-action="Imprime">see an PDF :D</a>

EM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EM.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Aluno" asp-action="Index">EM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EM - <a asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>